
"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { useState } from "react";
import { FileText, Download, Loader2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover";
import { Calendar } from "@/components/ui/calendar";
import { CalendarIcon } from "lucide-react";
import { format } from "date-fns";
import { cn } from "@/lib/utils";

// This file is effectively replaced by CreateContractForm.tsx
// It's kept here to avoid breaking existing imports if any, but should be considered deprecated.
// For new contract creation, use CreateContractForm.tsx

const formSchema = z.object({
  organizerName: z.string().min(2, { message: "Organizer name is required." }),
  artistName: z.string().min(2, { message: "Artist name is required." }),
  eventName: z.string().min(3, { message: "Event name is required." }),
  eventDate: z.date({ required_error: "Event date is required." }),
  eventLocation: z.string().min(3, { message: "Event location is required." }),
  scopeOfWork: z.string().min(10, { message: "Scope of work is required." }),
  paymentAmount: z.string().regex(/^\$?\d+(,\d{3})*(\.\d{2})?$/, { message: "Invalid payment amount format (e.g., $1,000 or 1000.00)." }),
  paymentTerms: z.string().min(5, { message: "Payment terms are required." }),
});

type ContractFormValues = z.infer<typeof formSchema>;

export default function ContractGeneratorForm() {
  const [generatedContract, setGeneratedContract] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  const form = useForm<ContractFormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      organizerName: "",
      artistName: "",
      eventName: "",
      eventDate: undefined,
      eventLocation: "",
      scopeOfWork: "",
      paymentAmount: "",
      paymentTerms: "50% upfront, 50% upon completion.",
    },
  });

  function generateContractText(values: ContractFormValues): string {
    return `
# Performance Agreement (Template)

**Date of Agreement:** ${format(new Date(), "PPP")}

**Between:**

1.  **The Organizer:**
    Name: ${values.organizerName}

2.  **The Artist:**
    Name: ${values.artistName}

**1. Event Details:**
   - Event Name: ${values.eventName}
   - Event Date: ${format(values.eventDate, "PPP")}
   - Event Location: ${values.eventLocation}

**2. Scope of Work:**
   ${values.scopeOfWork}

**3. Payment:**
   - Total Payment: ${values.paymentAmount}
   - Payment Terms: ${values.paymentTerms}

---
*Disclaimer: This is a sample template generated by OBSESSION. It is not legal advice.*
    `;
  }

  async function onSubmit(values: ContractFormValues) {
    setIsLoading(true);
    setGeneratedContract(null);
    await new Promise(resolve => setTimeout(resolve, 500));
    const contractText = generateContractText(values);
    setGeneratedContract(contractText);
    toast({
      title: "Contract Template Generated (Legacy)",
      description: "A draft contract has been created based on your input.",
    });
    setIsLoading(false);
  }

  const handleDownload = () => {
    if (!generatedContract) return;
    const blob = new Blob([generatedContract], { type: 'text/plain;charset=utf-8' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `LegacyContract_${form.getValues("eventName").replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(link.href);
  };

  return (
    <>
      <p className="text-sm text-destructive mb-4 p-2 border border-destructive/50 rounded-md">
        This is a legacy contract template generator. Please use the new "Create New Contract" form for a more structured approach.
      </p>
      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-8">
          <div className="grid md:grid-cols-2 gap-6">
            <FormField control={form.control} name="organizerName" render={({ field }) => (
              <FormItem><FormLabel>Organizer Name</FormLabel><FormControl><Input placeholder="Your Name / Company" {...field} /></FormControl><FormMessage /></FormItem>
            )} />
            <FormField control={form.control} name="artistName" render={({ field }) => (
              <FormItem><FormLabel>Artist Name</FormLabel><FormControl><Input placeholder="Artist's Name" {...field} /></FormControl><FormMessage /></FormItem>
            )} />
          </div>
          <Button type="submit" disabled={isLoading}>
            {isLoading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <FileText className="mr-2 h-4 w-4" />}
            Generate Legacy Template
          </Button>
        </form>
      </Form>

      {generatedContract && (
        <Card className="mt-8">
          <CardHeader className="flex flex-row items-center justify-between">
            <div>
              <CardTitle className="font-headline">Generated Legacy Template</CardTitle>
              <CardDescription>Review the template below. You can copy or download it.</CardDescription>
            </div>
            <Button onClick={handleDownload} variant="outline">
              <Download className="mr-2 h-4 w-4" /> Download (.txt)
            </Button>
          </CardHeader>
          <CardContent>
            <Textarea value={generatedContract} readOnly rows={15} className="font-code text-sm bg-muted/30" />
          </CardContent>
        </Card>
      )}
    </>
  );
}
